### ISSUE TITLE
Payment notification

### ISSUE THREAD

**Issue by FemiReis** [opeadeyomoye/hikashop-paystack#1]
Thanks for this plugin, it works great!
However, it seems the plugin does not revert to Hikashop to notifiy it that payment is successful so that Hikashop automatically confirms order and send payment receipt to the shop owner. As a result the order remains unconfirmed and the buyer is not able to have instant access to the product after payment.

**Comment by opeadeyomoye** [comment]
Interesting.

I'll check this out.

**Comment by FemiReis** [comment]
Great! Any updates? I must say it's a helpful plugin.

**Comment by opeadeyomoye** [comment]
@FemiReis did you set a callback URL on your Paystack dashboard?

The callback URL is where Paystack redirects to after your customer's payment has been processed. It should be set to 
```
https://your-site.com/index.php?option=com_hikashop&ctrl=checkout&task=notify&notif_payment=paystack&tmpl=component
```
Click here to configure this: https://dashboard.paystack.com/#/settings/developer

**Comment by opeadeyomoye** [comment]
Also, the plugin's settings page has the following option:

![screenshot from 2018-02-17 13-45-59](https://user-images.githubusercontent.com/13920568/36341160-2c538946-13ea-11e8-8df5-de22ef3b12a0.png)

Unless you're really sure what you're doing, you should leave that field blank.

**Comment by FemiReis** [comment]
Thanks boss!
But now it says "Secure Connection Failed" after payment has been made.
Please help.
Thanks.

**Comment by FemiReis** [comment]
Thanks boss!
But now it says "Secure Connection Failed" after payment has been made.
Please help.
Thanks.

**Comment by FemiReis** [comment]
Oh! I got it!
It was the s in https. I took it out and it worked great!
Weldone Ope! It's a great plugin you've built. I am taking Edwin Diaz's PHP From Begining to Master course from Udemy. If you don't mind I can consult with you for some tutoring too.
Thanks again for this plugin.
