### ISSUE TITLE
hikashop-paystack plugin not redirecting to hikashop after payment

### ISSUE THREAD

**Issue by raolowe** [opeadeyomoye/hikashop-paystack#4]
The plugin is working fine up to making payment. But after payment paystack needs to redirect to hikashop checkout so that orders earlier created can be changed to confirmed. Please update the plugin to address this issue

**Comment by livingsofttech** [comment]
Please what's the solution to this issue. I'm having the same problem.

**Comment by opeadeyomoye** [comment]
@raolowe @livingsofttech what are your Hikashop and Joomla! version numbers?

**Comment by livingsofttech** [comment]
> @raolowe @livingsofttech what are your Hikashop and Joomla! version numbers?

Joomla version is 3.8.1

Hikashop version is 4.0.3

**Comment by opeadeyomoye** [comment]
Thanks @livingsofttech .

@raolowe @livingsofttech I've fixed this in https://github.com/opeadeyomoye/hikashop-paystack/commit/94b979fccbdfcf889cff7be0b6ccb254383a9ba6 .

Please download [the latest version](https://github.com/opeadeyomoye/hikashop-paystack/archive/master.zip), install, and let me know if the problem still persists.

**Comment by livingsofttech** [comment]
> Thanks @livingsofttech .
> 
> @raolowe @livingsofttech I've fixed this in [94b979f](https://github.com/opeadeyomoye/hikashop-paystack/commit/94b979fccbdfcf889cff7be0b6ccb254383a9ba6) .
> 
> Please download [the latest version](https://github.com/opeadeyomoye/hikashop-paystack/archive/master.zip), install, and let me know if the problem still persists.

Thanks a bunch. I'll install and update you on the outcome.

Would i need to uninstall the previous version or i should install it over the previous

**Comment by opeadeyomoye** [comment]
You can install it over the previous version.

**Comment by raolowe** [comment]
Dear Ope,
It is ok now.
Thanks.

    On Sunday, 24 March 2019, 22:01:29 GMT+1, Ope Adeyomoye <notifications@github.com> wrote:  
 
 
Thanks @livingsofttech .

@raolowe @livingsofttech I've fixed this in 94b979f .

Please download the latest version, install, and let me know if the problem still persists.

**Comment by livingsofttech** [comment]
Yes

The plugin now works fine. 

Thanks for the effort. I heartily appreciate.
